### PR TITLE
create a log driver system, add loki driver, add prometheus metrics, update docs

### PR DESCRIPTION
**Pull request by jpetrucciani**
Apologies in advance for the mega-PR!

Do not feel obligated to merge this by any means if it is too gross/much (perhaps it would be better as a separate fork? I definitely don't want to push the burden of maintaining this onto you - let me know either way!)

In this PR, I've attempted to:
- shift things to a generic `LogDriver` system, which we can use to send Vercel logs to one or more outputs
- added a working implementation of the `LokiDriver` (tested with my own loki deployment, and with local methods)
- shifted CloudWatch to its own driver (though I have not extensively tested this since I don't have an active CloudWatch project to test with - though it may be interesting to make testing this easier!)
- added a local [nix](https://nixos.org/) development environment shell and some helpers to make testing easier
- add an option for exposing a [prometheus](https://prometheus.io/) `/metrics` endpoint to track a bunch of http and performance metrics
- updated the docs to better show available options, env vars, and defaults

Open to any and all feedback/suggestions - I am relatively new to Rust, compared to the other languages/ecosystems I normally live in!

### CODE REVIEW

**Comment by dacbd** [comment]
@jpetrucciani I would not call myself a rust expert either, but I like these improvements, I've been thinking of ways to improve testability and I think this is a set in the right direction.

If you want to manage your own fork feel free to, but I will happily accept the changes, and any future changes.

I think this is really good for any future users as there is now a clear path for how to add your own driver for any other future users.

**Comment by dacbd** [comment]
I will try to test some things out push any needed changes and then create a new release if everything checks out.

**Comment by jpetrucciani** [comment]
So long as you're cool with me sending more PRs! 😄 

Definitely let me know if things still work as expected with CloudWatch - I have a couple other drivers that I might want to add!

**Comment by dacbd** [comment]
For sure, keep them coming.

If you want to open an issue for each of the drivers you are thinking about
I can add one or two as well.

**Comment by jpetrucciani** [comment]
@dacbd sorry to comment on a previous PR - but did you have a chance to test out any of the changes for cloudwatch? it would be awesome to get a `0.0.3` release created for a docker image build!

**Pull request merged**
